package com.aukey.report.domain;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    private String name;    
    
    /**
     * 仓库类型
     */
    private String stockType;
    
    /**
     * 盘点装态
     */
    private int status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_id
     *
     * @return the value of stock.stock_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_id
     *
     * @param stockId the value for stock.stock_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getStockType()
    {
        return stockType;
    }

    public void setStockType(String stockType)
    {
        this.stockType = stockType;
    }

    public int getStatus()
    {
        return status;
    }

    public void setStatus(int status)
    {
        this.status = status;
    }
}