package com.aukey.report.domain;

import java.util.Date;

public class StarSign {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_sign.sign_type
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_sign.type_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_sign.user_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_sign.sign_time
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    private Date signTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_sign.sign_type
     *
     * @return the value of star_sign.sign_type
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_sign.sign_type
     *
     * @param signType the value for star_sign.sign_type
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public void setSignType(String signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_sign.type_id
     *
     * @return the value of star_sign.type_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_sign.type_id
     *
     * @param typeId the value for star_sign.type_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_sign.user_id
     *
     * @return the value of star_sign.user_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_sign.user_id
     *
     * @param userId the value for star_sign.user_id
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_sign.sign_time
     *
     * @return the value of star_sign.sign_time
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_sign.sign_time
     *
     * @param signTime the value for star_sign.sign_time
     *
     * @mbggenerated Wed Mar 01 17:03:56 CST 2017
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }
}
