drop table if exists storage_report;


CREATE TABLE `storage_report` (
  `storage_number` varchar(50) NOT NULL COMMENT '入库单号',
  `quality_inspection_number` varchar(50) DEFAULT NULL COMMENT '质检单号',
  `purchase_number` varchar(50) DEFAULT NULL COMMENT '采购单号',
  `supplier_id` int(11) DEFAULT NULL,
  `Inspector` varchar(45) DEFAULT NULL COMMENT '质检员Id',
  `warehouse_id` mediumint(6) DEFAULT NULL COMMENT '仓库名称Id',
  `muWarehouseName` varchar(50) DEFAULT NULL COMMENT '目标仓库',
  `nondefective_number` int(11) DEFAULT NULL COMMENT '入库良品数',
  `rejects_number` int(11) DEFAULT NULL COMMENT '不良品数',
  `spare_parts_number` int(11) DEFAULT NULL,
  `storage_location_code` varchar(50) DEFAULT NULL,
  `create_user` varchar(45) DEFAULT NULL COMMENT '入库员Id',
  `create_date` datetime DEFAULT NULL COMMENT '入库时间',
  `sku_code` varchar(50) DEFAULT NULL COMMENT 'SKU',
  `SKUname` varchar(500) DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL COMMENT '数据来源',
  `corporation_id` varchar(50) DEFAULT NULL COMMENT '法人主体id',
  `corporation_name` varchar(100) DEFAULT NULL COMMENT '法人主体',
  `transport_type` varchar(10) DEFAULT NULL,
  `transport_type_name` varchar(50) DEFAULT NULL COMMENT '运输方式',
  `is_tax` varchar(10) DEFAULT NULL,
  `is_tax_name` varchar(10) DEFAULT NULL COMMENT '是否退税',
  `reqUserName` varchar(255) DEFAULT NULL COMMENT '采购人员',
  `saleName` varchar(1000) DEFAULT NULL COMMENT '销售人员',
  `deptName` varchar(1000) DEFAULT NULL COMMENT '需求部门',
  `stockname` varchar(50) DEFAULT NULL,
  `stock_id` varchar(50) DEFAULT NULL,
  `tax_unit_price` decimal(10,2) DEFAULT NULL COMMENT '含税单价',
  `no_tax_price` decimal(10,2) DEFAULT NULL COMMENT '不含税单价',
  `supplier_name` varchar(255) DEFAULT NULL,
  `currency` varchar(10) DEFAULT NULL COMMENT '币种',
  PRIMARY KEY (`storage_number`),
  UNIQUE KEY `storage_number_key` (`storage_number`) USING BTREE,
  KEY `warehouse_id_name` (`warehouse_id`),
  KEY `purchase_number_index` (`purchase_number`) USING BTREE,
  KEY `quality_inspection_number_index` (`quality_inspection_number`) USING BTREE,
  KEY `create_date_index` (`create_date`) USING BTREE,
  KEY `sku_code_inedx` (`sku_code`) USING BTREE,
  KEY `deptName_index` (`deptName`) USING BTREE,
  KEY `muWarehouseName_index` (`muWarehouseName`) USING BTREE,
  KEY `corporation_id_index` (`corporation_id`) USING BTREE,
  KEY `transport_type_index` (`transport_type`) USING BTREE,
  KEY `is_tax_index` (`is_tax`) USING BTREE,
  KEY `stock_id_index` (`stock_id`) USING BTREE,
  KEY `saleName_index` (`saleName`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
