package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterPurchaseInTransit;

public interface CenterPurchaseInTransitService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_purchase_in_transit
     *
     * @mbggenerated Wed Jan 31 14:42:27 CST 2018
     */
    List<CenterPurchaseInTransit> selectAll(Map<String, Object> map);
    
    Integer selectAllCount(Map<String, Object> map);
}
