eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
    
#可能错误：found character '\t(TAB)' that cannot start any token
feign:
  hystrix:
    enabled: true