package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterFbaStockCount;

public interface CenterFbaStockCountService {
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_fba_stock_count
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    List<CenterFbaStockCount> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);

}
