package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterHeadInTransit;

public interface CenterHeadInTransitService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_head_in_transit
     *
     * @mbggenerated Fri Jan 26 14:51:56 CST 2018
     */
    List<CenterHeadInTransit> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
}
