package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterFbaInTransit;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CenterFbaInTransitMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_fba_in_transit
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    List<CenterFbaInTransit> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
    
}