package com.aukey.report.domain.centerstock;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Transient;

import org.springframework.stereotype.Component;

import com.aukey.auth.AuthType;
import com.aukey.auth.SecurityField;
import com.aukey.auth.SecurityTable;
/**
 * 店铺信息表
 * @author Administrator
 *
 */
@Entity
@Component
@SecurityTable
public class Account {
    /**
     *店铺ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Id
	@GeneratedValue
	@Column(name="account_id")
	@SecurityField(name="account_id",authType=AuthType.STORE)
    private Integer accountId;

    /**
     *店铺名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="account_name")
    private String accountName;

    /**
     *店铺简码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name_code
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="account_name_code")
    private String accountNameCode;

    /**
     *平台id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sales_platform_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="sales_platform_id")
    private Integer salesPlatformId;

    /**
     *分组id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_group_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="account_group_id")
    private Integer accountGroupId;

    /**
     *店铺状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_status
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="account_status")
    private String accountStatus;

    /**
     *销售人员
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.salesman_id
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="salesman_id")
    private Integer salesmanId;

    /**
     *备注
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.memo
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="memo")
    private String memo;

    /**
     *创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_user
     *
     * @mbg.generated Mon Aug 22 15:33:15 CST 2016
     */
	@Column(name="create_user")
    private String createUser;
	
	/**
	 * 创建时间
	 */
	@Column(name="create_time")
    private Date createTime;
	
	/**
	 * 更新人
	 */
	@Column(name="last_upd_user")
    private String lastUpdUser;
	
	/**
	 * 更新时间
	 */
	@Column(name="last_upd_time")
    private Date lastUpdTime;
	
	/**
	 * 店铺域名
	 */
	@Column(name="domain_name")
    private String domainName;

	public Integer getAccountId() {
		return accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getAccountNameCode() {
		return accountNameCode;
	}

	public void setAccountNameCode(String accountNameCode) {
		this.accountNameCode = accountNameCode;
	}

	public Integer getSalesPlatformId() {
		return salesPlatformId;
	}

	public void setSalesPlatformId(Integer salesPlatformId) {
		this.salesPlatformId = salesPlatformId;
	}

	public Integer getAccountGroupId() {
		return accountGroupId;
	}

	public void setAccountGroupId(Integer accountGroupId) {
		this.accountGroupId = accountGroupId;
	}

	public String getAccountStatus() {
		return accountStatus;
	}

	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus;
	}

	public Integer getSalesmanId() {
		return salesmanId;
	}

	public void setSalesmanId(Integer salesmanId) {
		this.salesmanId = salesmanId;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getLastUpdUser() {
		return lastUpdUser;
	}

	public void setLastUpdUser(String lastUpdUser) {
		this.lastUpdUser = lastUpdUser;
	}

	public Date getLastUpdTime() {
		return lastUpdTime;
	}

	public void setLastUpdTime(Date lastUpdTime) {
		this.lastUpdTime = lastUpdTime;
	}

	public String getDomainName() {
		return domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}
	@Transient
    private String cnName;

	public String getCnName() {
		return cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}
	@Transient
	private List<Integer> roleIds;

	public List<Integer> getRoleIds() {
		return roleIds;
	}

	public void setRoleIds(List<Integer> roleIds) {
		this.roleIds = roleIds;
	}
}