package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterOverseaTransportInTransit;

public interface CenterOverseaTransportInTransitService {
	
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_oversea_transport_in_transit
     *
     * @mbggenerated Fri Jan 26 15:44:32 CST 2018
     */
    List<CenterOverseaTransportInTransit> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);

}
