package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterOverseaWarehouse;

public interface CenterOverseaWarehouseService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_oversea_warehouse
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    List<CenterOverseaWarehouse> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
}
