package com.aukey.report.domain.centerstock;

import java.math.BigDecimal;
import java.text.DecimalFormat;

public class CenterOverseaWarehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_oversea_warehouse.warehouse_id
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    private Integer warehouseId;
    
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_oversea_warehouse.sku
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_oversea_warehouse.no_lock_quantity
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    private BigDecimal noLockQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_oversea_warehouse.lock_quantity
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    private BigDecimal lockQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_oversea_warehouse.quantity
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    private BigDecimal quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_oversea_warehouse.warehouse_id
     *
     * @return the value of center_oversea_warehouse.warehouse_id
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }
    
    public String getWarehouseName() {
		return warehouseName;
	}

	public void setWarehouseName(String warehouseName) {
		this.warehouseName = warehouseName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_oversea_warehouse.warehouse_id
     *
     * @param warehouseId the value for center_oversea_warehouse.warehouse_id
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_oversea_warehouse.sku
     *
     * @return the value of center_oversea_warehouse.sku
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_oversea_warehouse.sku
     *
     * @param sku the value for center_oversea_warehouse.sku
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

	public BigDecimal getNoLockQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(noLockQuantity));
	}

	public void setNoLockQuantity(BigDecimal noLockQuantity) {
		this.noLockQuantity = noLockQuantity;
	}

	public BigDecimal getLockQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(lockQuantity));
	}

	public void setLockQuantity(BigDecimal lockQuantity) {
		this.lockQuantity = lockQuantity;
	}

	public BigDecimal getQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(quantity));
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

  
}