package com.aukey.report.domain.centerstock;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Date;

public class CenterFbaInTransit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_in_transit.fba_return_plan_no
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    private String fbaReturnPlanNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_in_transit.warehouse_id
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    private Integer warehouseId;
    
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_in_transit.sku
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_in_transit.quantity
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_in_transit.deliver_date
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    private Date deliverDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_fba_in_transit.fba_return_plan_no
     *
     * @return the value of center_fba_in_transit.fba_return_plan_no
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public String getFbaReturnPlanNo() {
        return fbaReturnPlanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_fba_in_transit.fba_return_plan_no
     *
     * @param fbaReturnPlanNo the value for center_fba_in_transit.fba_return_plan_no
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public void setFbaReturnPlanNo(String fbaReturnPlanNo) {
        this.fbaReturnPlanNo = fbaReturnPlanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_fba_in_transit.warehouse_id
     *
     * @return the value of center_fba_in_transit.warehouse_id
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_fba_in_transit.warehouse_id
     *
     * @param warehouseId the value for center_fba_in_transit.warehouse_id
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
    
    public String getWarehouseName() {
		return warehouseName;
	}

	public void setWarehouseName(String warehouseName) {
		this.warehouseName = warehouseName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_fba_in_transit.sku
     *
     * @return the value of center_fba_in_transit.sku
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_fba_in_transit.sku
     *
     * @param sku the value for center_fba_in_transit.sku
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

	public BigDecimal getQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(quantity));
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_fba_in_transit.deliver_date
     *
     * @return the value of center_fba_in_transit.deliver_date
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public Date getDeliverDate() {
        return deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_fba_in_transit.deliver_date
     *
     * @param deliverDate the value for center_fba_in_transit.deliver_date
     *
     * @mbggenerated Fri Jan 26 11:08:38 CST 2018
     */
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }
}