package com.aukey.report.domain.centerstock;

import java.math.BigDecimal;
import java.text.DecimalFormat;

public class CenterFbaStockCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_stock_count.sku
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_stock_count.sale_quantity
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    private BigDecimal saleQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_stock_count.no_sale_quantity
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    private BigDecimal noSaleQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_fba_stock_count.quantity
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    private BigDecimal quantity;

    
    private Integer accountId;
    
    private String accountName;
    
    private Integer siteGroupId;
    
    private String area;
    
    private String amazonSku;
    
    private String fnsku;
    
    private String productName;
    
    private BigDecimal yourPrice;
    
    private BigDecimal reservedQuantity;
    
    
    
	public Integer getAccountId() {
		return accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Integer getSiteGroupId() {
		return siteGroupId;
	}

	public void setSiteGroupId(Integer siteGroupId) {
		this.siteGroupId = siteGroupId;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAmazonSku() {
		return amazonSku;
	}

	public void setAmazonSku(String amazonSku) {
		this.amazonSku = amazonSku;
	}

	public String getFnsku() {
		return fnsku;
	}

	public void setFnsku(String fnsku) {
		this.fnsku = fnsku;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public BigDecimal getYourPrice() {
		return yourPrice;
	}

	public void setYourPrice(BigDecimal yourPrice) {
		this.yourPrice = yourPrice;
	}
	
	

	public BigDecimal getReservedQuantity() {
		return reservedQuantity;
	}

	public void setReservedQuantity(BigDecimal reservedQuantity) {
		this.reservedQuantity = reservedQuantity;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_fba_stock_count.sku
     *
     * @return the value of center_fba_stock_count.sku
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_fba_stock_count.sku
     *
     * @param sku the value for center_fba_stock_count.sku
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

	public BigDecimal getSaleQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(saleQuantity));
	}

	public void setSaleQuantity(BigDecimal saleQuantity) {
		this.saleQuantity = saleQuantity;
	}

	public BigDecimal getNoSaleQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(noSaleQuantity));
	}

	public void setNoSaleQuantity(BigDecimal noSaleQuantity) {
		this.noSaleQuantity = noSaleQuantity;
	}

	public BigDecimal getQuantity() {
		return new BigDecimal(new DecimalFormat("#.000000").format(quantity));
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

    
}