package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterDomesticTransferWarehouse;

public interface CenterDomesticTransferWarehouseService {
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_domestic_transfer_warehouse
     *
     * @mbggenerated Fri Jan 26 14:12:33 CST 2018
     */
    List<CenterDomesticTransferWarehouse> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);

}
