package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterOverseaWarehouse;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CenterOverseaWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_oversea_warehouse
     *
     * @mbggenerated Wed Jan 31 16:51:58 CST 2018
     */
    List<CenterOverseaWarehouse> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
}