package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterFbaStockCount;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface CenterFbaStockCountMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_fba_stock_count
     *
     * @mbggenerated Fri Jan 26 14:29:35 CST 2018
     */
    List<CenterFbaStockCount> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
}