package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterPurchaseInTransit;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CenterPurchaseInTransitMapper {
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_purchase_in_transit
     *
     * @mbggenerated Wed Jan 31 14:42:27 CST 2018
     */
    List<CenterPurchaseInTransit> selectAll(Map<String, Object> map);
    
    Integer selectAllCount(Map<String, Object> map);
}