package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterSkuDepartRelation;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CenterSkuDepartRelationMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_sku_depart_relation
     *
     * @mbggenerated Fri Mar 02 09:51:27 CST 2018
     */
    int insert(CenterSkuDepartRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_sku_depart_relation
     *
     * @mbggenerated Fri Mar 02 09:51:27 CST 2018
     */
    List<CenterSkuDepartRelation> selectAll(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_sku_depart_relation
     *
     * @mbggenerated Fri Mar 02 09:51:27 CST 2018
     */
    int updateCenterSkuDepartRelation(CenterSkuDepartRelation record);
    
    
    Integer selectAllCount(Map<String, Object> map);
}