package com.aukey.report.domain.stockverify;

import java.math.BigDecimal;

public class StockVerifyReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.stock_verify_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Long stockVerifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.sku_code
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private String skuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.wsku
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private String wsku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.sku_name
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.category_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer categoryId;
    
    private String categoryName;

    private String departmentName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.stock_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer stockId;
    
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.system_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer systemBoxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.system_single_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer systemSingleBoxNumber;

    public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.system_number_sum
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer systemNumberSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.length
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.width
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.height
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.volume
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.weight
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.price
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.in_stock_count
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer inStockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_verify_report.difference_quantity
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    private Integer differenceQuantity;

    
    

	
	
	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.stock_verify_id
     *
     * @return the value of stock_verify_report.stock_verify_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Long getStockVerifyId() {
        return stockVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.stock_verify_id
     *
     * @param stockVerifyId the value for stock_verify_report.stock_verify_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setStockVerifyId(Long stockVerifyId) {
        this.stockVerifyId = stockVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.sku_code
     *
     * @return the value of stock_verify_report.sku_code
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.sku_code
     *
     * @param skuCode the value for stock_verify_report.sku_code
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.wsku
     *
     * @return the value of stock_verify_report.wsku
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public String getWsku() {
        return wsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.wsku
     *
     * @param wsku the value for stock_verify_report.wsku
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setWsku(String wsku) {
        this.wsku = wsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.sku_name
     *
     * @return the value of stock_verify_report.sku_name
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.sku_name
     *
     * @param skuName the value for stock_verify_report.sku_name
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.category_id
     *
     * @return the value of stock_verify_report.category_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.category_id
     *
     * @param categoryId the value for stock_verify_report.category_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.stock_id
     *
     * @return the value of stock_verify_report.stock_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.stock_id
     *
     * @param stockId the value for stock_verify_report.stock_id
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.system_box_number
     *
     * @return the value of stock_verify_report.system_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getSystemBoxNumber() {
        return systemBoxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.system_box_number
     *
     * @param systemBoxNumber the value for stock_verify_report.system_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setSystemBoxNumber(Integer systemBoxNumber) {
        this.systemBoxNumber = systemBoxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.system_single_box_number
     *
     * @return the value of stock_verify_report.system_single_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getSystemSingleBoxNumber() {
        return systemSingleBoxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.system_single_box_number
     *
     * @param systemSingleBoxNumber the value for stock_verify_report.system_single_box_number
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setSystemSingleBoxNumber(Integer systemSingleBoxNumber) {
        this.systemSingleBoxNumber = systemSingleBoxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.system_number_sum
     *
     * @return the value of stock_verify_report.system_number_sum
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getSystemNumberSum() {
        return systemNumberSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.system_number_sum
     *
     * @param systemNumberSum the value for stock_verify_report.system_number_sum
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setSystemNumberSum(Integer systemNumberSum) {
        this.systemNumberSum = systemNumberSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.length
     *
     * @return the value of stock_verify_report.length
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.length
     *
     * @param length the value for stock_verify_report.length
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.width
     *
     * @return the value of stock_verify_report.width
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.width
     *
     * @param width the value for stock_verify_report.width
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.height
     *
     * @return the value of stock_verify_report.height
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.height
     *
     * @param height the value for stock_verify_report.height
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.volume
     *
     * @return the value of stock_verify_report.volume
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.volume
     *
     * @param volume the value for stock_verify_report.volume
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.weight
     *
     * @return the value of stock_verify_report.weight
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.weight
     *
     * @param weight the value for stock_verify_report.weight
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.price
     *
     * @return the value of stock_verify_report.price
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.price
     *
     * @param price the value for stock_verify_report.price
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.in_stock_count
     *
     * @return the value of stock_verify_report.in_stock_count
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getInStockCount() {
        return inStockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.in_stock_count
     *
     * @param inStockCount the value for stock_verify_report.in_stock_count
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setInStockCount(Integer inStockCount) {
        this.inStockCount = inStockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_verify_report.difference_quantity
     *
     * @return the value of stock_verify_report.difference_quantity
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public Integer getDifferenceQuantity() {
        return differenceQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_verify_report.difference_quantity
     *
     * @param differenceQuantity the value for stock_verify_report.difference_quantity
     *
     * @mbggenerated Fri Mar 23 15:19:52 CST 2018
     */
    public void setDifferenceQuantity(Integer differenceQuantity) {
        this.differenceQuantity = differenceQuantity;
    }
}