package com.aukey.report.service.centerstock;

import java.util.List;
import java.util.Map;

import com.aukey.report.domain.centerstock.CenterStockQuery;
import com.aukey.report.domain.centerstock.CenterStockReport;

public interface CenterStockReportService {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_stock_report
     *
     * @mbggenerated Wed Jan 17 17:08:28 CST 2018
     */
    List<CenterStockReport> selectAll(Map<String, Object> map);

    Integer selectAllCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectFbaStock(Map<String, Object> map);
    
    Integer selectFbaStockCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectOverseaStockTransfer(Map<String, Object> map);
    
    Integer selectOverseaStockTransferCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectFirstAirTransfer(Map<String, Object> map);
    
    Integer selectFirstAirTransferCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectTransferWarehouse(Map<String, Object> map);
    
    Integer selectTransferWarehouseCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectPurchaseTransfer(Map<String, Object> map);
    
    Integer selectPurchaseTransferCount(Map<String, Object> map);
    
    List<CenterStockQuery> selectFbaTransfer(Map<String, Object> map);
    
    Integer selectFbaTransferCount(Map<String, Object> map);
    
    List<Map<String, Object>> findAllOrgs(Map<String, Object> map);
}
