package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterDomesticTransferWarehouse;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface CenterDomesticTransferWarehouseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_domestic_transfer_warehouse
     *
     * @mbggenerated Fri Jan 26 14:12:33 CST 2018
     */
    List<CenterDomesticTransferWarehouse> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
    
}