package com.aukey.report.mapper.centerstock;

import com.aukey.report.domain.centerstock.CenterOverseaTransportInTransit;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CenterOverseaTransportInTransitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_oversea_transport_in_transit
     *
     * @mbggenerated Fri Jan 26 15:44:32 CST 2018
     */
    //int insert(CenterOverseaTransportInTransit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_oversea_transport_in_transit
     *
     * @mbggenerated Fri Jan 26 15:44:32 CST 2018
     */
    List<CenterOverseaTransportInTransit> selectAll(Map<String, Object> map);
    Integer selectAllCount(Map<String, Object> map);
}